//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotographerPicture
    {
        public int ID { get; set; }
        public string PictureName { get; set; }
        public int PhotographerID { get; set; }
    
        public virtual Photographer Photographer { get; set; }
    }
}
